spring:
  redis:
    username:
    password: franktw
    host: 127.0.0.1
    port: 6379
    connect-timeout: 1000
    database: 9
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqllite/manage.db
    username:
    password:
